name: US Stock Scanner (Public Runner)

on:
  schedule:
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone Private Repo
        run: |
          git clone https://${{ secrets.MY_PRIVATE_TOKEN }}@github.com/beep2323/usmarket2.git private_code
          
          cd private_code
          pip install yfinance pandas openpyxl requests googletrans==4.0.0-rc1
          python early_scanner.py --use-data-cache
          
      - name: Send TG Notification
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          cd private_code
          python notif.py us
